M48
; DRILL file {KiCad 8.0.1} date 2024-04-15T18:30:33+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-15T18:30:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X4.0689Y-1.9567
X4.0689Y-5.0118
X7.2461Y-1.9567
X7.2461Y-5.0118
M30
